### ISSUE TITLE
References section missing from final build

### ISSUE THREAD

**Issue by ludwigschubert** [distillpub/post--multimodal#6]
- [x] Footnote 43 has placeholder text ("explain the neuron is a time period and the language side thinks of it as embarrassing
43 ")

**Comment by ludwigschubert** [comment]
- [x] References section doesn't seem to render?

**Comment by ludwigschubert** [comment]
Fixed around 48e435468932a86894a889afa7ea1125a97c525d :-)

**Comment by mateon1** [comment]
Footnote 43 still has that issue on the live article, I'm not sure if I should create a separate issue since this one already mentions it.

**Comment by ludwigschubert** [comment]
Hi @mateon1 , good catch — the issue is fixed on this repository, though, and its deploy is stuck upstream due to some distill deployment inconsistencies I inadvertently introduced. It’ll be deployed as soon as we can. Thanks for reporting.
